# Neovim version of NeoComplete for autocompleting code.
# https://github.com/Shougo/deoplete.vim
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  " Begin autocompleting at 1 character
  let g:deoplete#auto_complete_start_leng = 1
  " auto_select id done with completeopt+=noinsert

  " Patterns when to begin omnicompletion
  let g:deoplete#omni#input_patterns = get(g:, 'deoplete#omni#input_patterns', {})
  let g:deoplete#omni#input_patterns.php = '\w+|[^. \t]->\w*\|\w+::\w*'
  let g:deoplete#omni#input_patterns.css = '\w+|\w+[):;]?\s+\w*'
  let g:deoplete#omni#input_patterns.html = '<[^>]*\s[[:alnum:]-]*'
  let g:deoplete#omni#input_patterns.javascript = '[^. \t0-9]\.([a-zA-Z_]\w*)?'

  " Maximum targets
  let g:deoplete#max_list = 10
'''
